### ISSUE TITLE
`bank_table`: add `max-preemptible-after` column

### ISSUE THREAD

**Issue by cmoussa1** [flux-framework/flux-accounting#553]
The `bank_table` does not have a way to track a max `preemptible-after` value for a certain bank. This kind of information is needed to enforce a limit on association-set `preemptible-after` values on their jobs as well as set a default on their job in the case where the association does not set one on their own.

Because this might be specific to a bank, its default should be to require no preemption. This would also follow the `preemptible-after` attribute defined in [RFC 14](https://github.com/flux-framework/rfc/blob/master/spec_14.rst).

The column in the `bank_table` should be a `real` number that has no default value (which would indicate that there is no preemption required for this bank and should retroactively support banks already defined), but when defined, represents:

> A floating point number greater than or equal to zero representing job run time after which the job MAY be canceled in order to make way for other jobs. A value of zero indicates that the job is immediately preemptible. The attribute SHALL NOT be set if the job is never preemptible.

This value should be able to be specified on the command line when first adding a bank as well as be edited after the bank is added.

---

```[tasklist]
### Tasks
- [ ] add `max-preemptible-after` column to `bank_table`
- [ ] update flux-accounting database schema
- [ ] add `max-preemptible-after` column to output of `view-bank`
- [ ] add `--max-preemptible-after` optional arguments to `add-bank`, `edit-bank`
```
